### ISSUE TITLE
Invalid Captcha

### ISSUE THREAD

**Issue by SpraxDev** [MCGameInfo/mcgame.info#10]
When I try to login as spRaX2013 instead of Sprax2013 - It tells me that my Account does not exist.

When i fix the Username and want to login the Captcha is still verified (green check) but I can't login because the Captcha-Resonse is invalid.

The Captcha should be resetted when the login failed

![screenshot_1](https://user-images.githubusercontent.com/7331598/28785421-b2cfd654-7616-11e7-9b22-5f2b17ed8f02.png)

**Comment by InventivetalentDev** [comment]
Will check :)
