### ISSUE TITLE
Can't register, request 502s

### ISSUE THREAD

**Issue by MiniDigger** [MCGameInfo/mcgame.info#2]
https://api.mcgame.info/account/checkUser?username=MiniDigger (which is checked when I click register) returns a 502 and thus doesn't let me register.

**Comment by InventivetalentDev** [comment]
Please try again, the server crashed for second there :)
(Great start, *cough*)

**Comment by MiniDigger** [comment]
works now, not really sure if I like the popup tho (since chrome blocks them by default), couldn't you just do a modal with a iframe or something like that?

**Comment by InventivetalentDev** [comment]
> couldn't you just do a modal with a iframe or something like that? 

Yeah, I was also thinking about alternatives, will probably change it.
