### ISSUE TITLE
Can't login and see Server-List

### ISSUE THREAD

**Issue by SpraxDev** [MCGameInfo/mcgame.info#3]
I created a Account and now there is only a Steve Skin-Head and it says "Welcome back, !" (No Name)
The Server-List is empty (bevor creating an account: 2 Servers)

When I click on the Login-Button nothing happens

![screenshot_1](https://user-images.githubusercontent.com/7331598/28723732-f82d212c-73b7-11e7-87fd-33a736368783.png)

**Comment by InventivetalentDev** [comment]
Please try again, the server crashed :)

**Comment by SpraxDev** [comment]
Servers are back now but I can't login

When I login it says "Invalid password" or "User Not found"

When I want to create a new User it says "User already exists"

**Comment by InventivetalentDev** [comment]
Hmm, weird. The server probably crashed while the login was in progress, so it didn't save your password properly. I'll just reset your account quickly c:

**Comment by SpraxDev** [comment]
It's working now - thanks :D

Maybe you could fix the login: I'm using KeePass as a PasswordManager. Together with an Community Addon KeeFox (for FireFox).

When I use it to Auto-Fill the Form and click login it's saying the Username-Lenght is too short. I need to write at least one char in username and password. Then I can Auto-Fill and Login. Kind of annoying but it's not only your website xD

**Comment by InventivetalentDev** [comment]
Yeah, I noticed similar issues using LastPass on chrome recently. Will look into it :)

**Comment by SpraxDev** [comment]
Great :)
