### ISSUE TITLE
Domain records not recognized

### ISSUE THREAD

**Issue by SpraxDev** [MCGameInfo/mcgame.info#4]
My Network (Waterfall [BungeeCord fork]) is running on CherryBread.net - I can join and everything. But the website tells me that it can't read my Domain records. (or validate - Something like that)

My Proxy-Console tells me:
`
16:55:42 [WARNUNG] [MCGameInfo] Got non-OK ping response from the API
16:55:42 [WARNUNG] [MCGameInfo] {"valid":false,"msg":"Server not found","status":"err"}
`

But MCGameInfo is a nice idea ;D

**Comment by InventivetalentDev** [comment]
Please click the warning icon in your server list 
![](https://i.inventivetalent.org/2017/07/28/c1849fbbd7_chrome.png)

and make sure you've set up your TXT records properly
![](https://i.inventivetalent.org/2017/07/28/0e9a41209d_chrome.png)

**Comment by SpraxDev** [comment]
Oh xD

Okay but now it tells me that there a no valid TXT records.

Do I need to create 2 record or only one?

![screenshot_2](https://user-images.githubusercontent.com/7331598/28725363-80aac522-73bd-11e7-9917-5dd92e5cecce.png)

**Comment by SpraxDev** [comment]
Okay sorry - Just needed to wait some minutes

Working fine

Thanks :)
