### ISSUE TITLE
Push notifications don't work

### ISSUE THREAD

**Issue by MiniDigger** [MCGameInfo/mcgame.info#5]
Just enabled push notifications and all triggers, allowed it in chrome but I don't get a notification when I send a friend request to my second account or if one of the accounts join the test server. the interface shows that the players are online correctly.

**Comment by InventivetalentDev** [comment]
Should be working now (at least in chrome)

**Comment by MiniDigger** [comment]
yeah, they worked after toggling it in the settings now. 
you need to serialize the server object tho ^^
![https://i.imgur.com/AUvFhUw.png](https://i.imgur.com/AUvFhUw.png)
also, would it be possible to hide it when clicking on it? currently it just stays there for ages and you need to press the small X to get rid of it.
